//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec.api.fm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public int id { get; set; }
    }
}
