//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec.res.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gasto()
        {
            this.material = new HashSet<material>();
        }
    
        public string proveedor { get; set; }
        public string foto { get; set; }
        public string numero_factura { get; set; }
        public int id_compra { get; set; }
        public int id_etapa { get; set; }
        public Nullable<int> semana { get; set; }
        public int id_obra { get; set; }
    
        public virtual etapa etapa { get; set; }
        public virtual obra obra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<material> material { get; set; }
    }
}
