//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec.res.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class labora_en
    {
        public int id_empleado { get; set; }
        public int id_obra { get; set; }
        public Nullable<int> semana { get; set; }
        public Nullable<double> horas_laboradas { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual obra obra { get; set; }
    }
}
