//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec.res.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public obra()
        {
            this.diseña = new HashSet<diseña>();
            this.gasto = new HashSet<gasto>();
            this.labora_en = new HashSet<labora_en>();
            this.trabaja_en = new HashSet<trabaja_en>();
            this.tiene = new HashSet<tiene>();
            this.requiere = new HashSet<requiere>();
        }
    
        public string nombre_obra { get; set; }
        public Nullable<int> ubicacion { get; set; }
        public Nullable<int> cantidad_habitaciones { get; set; }
        public Nullable<int> cantidad_banos { get; set; }
        public Nullable<int> cantidad_pisos { get; set; }
        public Nullable<double> area_construccion { get; set; }
        public Nullable<int> area_lote { get; set; }
        public Nullable<int> propietario { get; set; }
        public int id { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diseña> diseña { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gasto> gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<labora_en> labora_en { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabaja_en> trabaja_en { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tiene> tiene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requiere> requiere { get; set; }
        public virtual ubicacion ubicacion1 { get; set; }
    }
}
