//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec.res.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requiere
    {
        public int id_etapa { get; set; }
        public string codigo_material { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual material material { get; set; }
        public virtual etapa etapa { get; set; }
    }
}
