//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec.res.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiene
    {
        public int id_etapa { get; set; }
        public int id_obra { get; set; }
        public Nullable<System.DateTime> fecha_incio { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
    
        public virtual etapa etapa { get; set; }
        public virtual obra obra { get; set; }
    }
}
